INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR")VALUES(1,true, 'a',1.50);
INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR")VALUES(2,false, 'b',3.50);
INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR")VALUES(3,true, 'c',7.50);