INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR","ATIVO")VALUES(1,true, 'a',1.50,true,);
INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR","ATIVO")VALUES(2,false, 'b',3.50,false);
INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR","ATIVO")VALUES(3,false, 'c',7.50,true);
INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR","ATIVO")VALUES(4,true, 'a',1.50,true);
INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR","ATIVO")VALUES(5,false, 'b',3.50,false);
INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR","ATIVO")VALUES(6,false, 'c',7.50,true);


