INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR","STATUS")VALUES(1,true, 'a',1.50,true,);
INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR","STATUS")VALUES(2,false, 'b',3.50,false);
INSERT INTO "PUBLIC"."PRODUTO"("ID","IS_SERVICO","NOME","VALOR","STATUS")VALUES(3,true, 'c',7.50,true,);


